### ISSUE TITLE
Maybe add a formatter?

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#16]
This becomes especially relevant in case external devs want to contribute.

I personally grew to like the [black](https://github.com/psf/black) formatter (after an initial phase of wtf), that I use together with [isort](https://pycqa.github.io/isort/) in git hooks through pre-commit.

**Comment by opcode81** [comment]
The code's formatting is fine. We all know how to format code neatly enough.
Those who want to can apply auto-formatting to the code they contribute.

**Comment by MischaPanch** [comment]
Ok, then I will maybe apply black for new code that I write
