### ISSUE TITLE
Allow possibility to install supported optional deps with pip

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#21]
This can be done through the extras_require flag so we support something like pip install sensai[tensorflow] and so on

**Comment by MischaPanch** [comment]
Ah, this is already possible, I missed that! I will simply add the full option as well

**Comment by opcode81** [comment]
We should consider switching to conda for venv configuration (using the YAML-based environment specification: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment). 
Installing libraries like tensorflow via conda has considerable advantages. In particular, the conda-based installation will install CUDA and CuDNN in versions that match the tf installation, whereas the pip-based installation requires that the matching installations be provided externally, which is extremely painful.
