### ISSUE TITLE
Support conda for venv configuration

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#24]
We should consider switching to conda for venv configuration (using the YAML-based environment specification: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment). 
Installing libraries like tensorflow via conda has considerable advantages. In particular, the conda-based installation will install CUDA and CuDNN in versions that match the tf installation, whereas the pip-based installation requires that the matching installations be provided externally, which is extremely painful.

_Originally posted by @opcode81 in https://github.com/jambit/sensAI/issues/21#issuecomment-735282306_

**Comment by MischaPanch** [comment]
That would be nice. One thing to keep in mind though is that we build and test with tox which is bound to use pip. Ideally, we should support both without the conda support getting in the way of the tox build. There are some attempts at bringing tox and conda together like [this one](https://github.com/tox-dev/tox-conda). I have never tried it and it might be complicated to really make it work.

**Comment by opcode81** [comment]
tox-conda being developed by the tox devs themselvers, apparently, I think chances of this working out aren't too slim.

**Comment by opcode81** [comment]
For development purposes, commit d39f797ffe76cabce96c452d0ca0d5f5b1994d9b has added environment.yml, which includes requirements.txt and can be used instead of requirements-dev.txt (which still exists, however).
