### ISSUE TITLE
Generalize TorchDataSet to DataSet using batches of pd.DataFrame

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#25]
Since I will probably write some data loaders for images anyway, I wonder whether this can be geneIralized a bit and used in the rest of sensai. For example, we might have a base DataSet that generates batches of numpy arrays and convert them to tensors either in a child class or directly in the methods consuming the dataset

_Originally posted by @MischaPanch in https://github.com/jambit/sensAI/pull/23#discussion_r532200628_

**Comment by MischaPanch** [comment]
Related to #40

**Comment by opcode81** [comment]
Abstraction `Vectoriser` now provides the link between DataFrames and tensors

**Comment by opcode81** [comment]
Closing this because we already have sufficient batching support (including the case where the batches are generated on demand via "dynamic tensorisation") for torch models. No additional features are required at this time.
