### ISSUE TITLE
Cache .tox and possible apt packages

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#31]
This is already done in the gitlab pipeline, we should also to it on github. Probably won't be totally trivial though

**Comment by opcode81** [comment]
Why?

**Comment by MischaPanch** [comment]
It would significantly speed up the build, no need to recreate the environments and download the dependencies each time. I might make a PR today or tomorrow

**Comment by opcode81** [comment]
Build speed is not really important, so only do this if you can guarantee that there won't be adverse effects.
