### ISSUE TITLE
Maybe improve _predict interface in VectorModel

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#34]
To make this "cleaner", we could consider changing the interface of `_predict` to not return a DF but a more low-level result instead and make `predict` construct the DF correctly.

_Originally posted by @opcode81 in https://github.com/jambit/sensAI/pull/33#discussion_r539355532_

**Comment by opcode81** [comment]
Implements should be allowed to return either a pd.DataFrame, a pd.Series (if it's a one-column output) or an np.array - and VectorModel should take care of constructing the proper DF from it (and ensure that it has the right index).

**Comment by opcode81** [comment]
Has been addressed with commit 5002840360c22adf1a0046cc73907bd0a26f6536
