### ISSUE TITLE
Objects such as DFTs and Fgens should know whether they actually require fitting ...

### ISSUE THREAD

**Issue by MischaPanch** [jambit/sensAI#35]
As a user, I would object to receiving warnings that do not apply. Ideally, we should not warn that there might be a problem but _know_ if there is a problem (by having the components be aware of the fitting requirement) - and throw an exception iff so.

_Originally posted by @opcode81 in https://github.com/jambit/sensAI/pull/33#discussion_r539341929_

**Comment by opcode81** [comment]
... such that we can raise an exception where appropriate and drop the warning in RuleBasedModel whenever it doesn't apply.
