### ISSUE TITLE
Notebook Test Failure: PyTorch-Lightning ImportError

### ISSUE THREAD

**Issue by opcode81** [jambit/sensAI#58]
@MischaPanch, [new failure encountered](https://github.com/jambit/sensAI/runs/3219457853?check_suite_focus=true#step:9:361).
Looks like the version of pytorch-lightning being used is incompatible with the version of torch being used; probably due to the relaxed version specification (`pytorch-lightning~=1.1`) in tox.ini.

_Originally posted by @opcode81 in https://github.com/jambit/sensAI/issues/57#issuecomment-890972025_

**Comment by MischaPanch** [comment]
Ah, that's unfortunate. I'll have a look

**Comment by opcode81** [comment]
Fixed with commit 84ecaf12ee0fd5b2bbe1524e07aa9f3cad82ca39.
